# Generated by Django 5.0.3 on 2024-04-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='movies/')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('run', models.IntegerField(default=12345678, primary_key=True, serialize=False, verbose_name='run')),
                ('username', models.CharField(default='username_por_defecto', max_length=10, verbose_name='username')),
                ('nombres', models.CharField(default='Nombre por defecto', max_length=60)),
                ('apellidos', models.CharField(default='Apellido por defecto', max_length=100)),
                ('password', models.CharField(default='password_por_defecto', max_length=255)),
                ('perfil', models.IntegerField(blank=True, null=True, verbose_name='perfil')),
            ],
        ),
    ]
