# Generated by Django 5.0.3 on 2024-04-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('run', models.IntegerField(default=12345678, primary_key=True, serialize=False, verbose_name='run')),
                ('username', models.CharField(default='username_por_defecto', max_length=10, verbose_name='username')),
                ('nombres', models.CharField(default='Nombre por defecto', max_length=60)),
                ('apellidos', models.CharField(default='Apellido por defecto', max_length=100)),
                ('password', models.CharField(default='password_por_defecto', max_length=255)),
                ('perfil', models.IntegerField(blank=True, null=True, verbose_name='perfil')),
            ],
        ),
    ]
