# Generated by Django 5.0.3 on 2024-04-16 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=100)),
            ],
        ),
    ]
